version: 2
jobs:
  build:
    docker:
      - image: node:14-alpine
    working_directory: ~/repo

    steps:
      - checkout
      - run: apk add --no-cache git
      # Download and cache dependencies
      

      # run tests!
      - run: yarn lint

      - run: yarn build