// TODO: Convert to Enum after TypeScript integration.

export const AUTH_TYPE = {
  EXTENSION: 'extension',
  TWITTER: 'twitter',
  ETH: 'ETH',
  USERNAME: 'username'
};

export const LOCAL_STORAGE_KEYS = {
  ETH_AUTH: 'YUP_ETH_AUTH',
  YUP_REWARDS: 'YUP_CLAIM_RWRDS',
  THEME_MODE: 'THEME_MODE',
  TWITTER_INFO: 'twitterMirrorInfo',
  ETH_NOTIFICATION_TIMESTAMP: 'ETH_NOTIFICATION_TIMESTAMP',
  CHECK_BRAVE: 'CHECK_BRAVE'
};

export const REACT_QUERY_KEYS = {
  YUP_LIST_FILTER: 'YUP_LIST_FILTER',
  YUP_LIST: 'YUP_LIST',
  YUP_COLLECTION: 'YUP_COLLECTION',
  YUP_RECOMMENDATION: 'YUP_RECOMMENDATION',
  YUP_INITIAL_VOTES: 'YUP_INITIAL_VOTES',
  YUP_SOCIAL_LEVEL: 'YUP_SOCIAL_LEVEL',
  FOLLOWING: 'FOLLOWING',
  FOLLOWER: 'FOLLOWER',
  USER_POSTS: 'USER_POSTS',
  SEARCH_POSTS: 'SEARCH_POSTS',
  SEARCH_PEOPLE: 'SEARCH_PEOPLE',
  SEARCH_COLLECTIONS: 'SEARCH_COLLECTIONS',
  USER_COLLECTIONS: 'USER_COLLECTIONS',
  USER_NOTIFICATIONS: 'USER_NOTIFICATIONS',
  FARCASTER_PARENT: 'FARCASTER_PARENT',
  USER_LIKES: 'USER_LIKES',
  YUP_FEED: 'YUP_FEED',
  POST:' POST'
};

export const LOADER_TYPE = {
  DEFAULT: 'default',
  USER_CONNECTION: 'user_connection',
  FEED: 'feed',
  NOTIFICATION: 'notification',
  TOP_BAR: 'topbar'
};
