name: Lint

on:
  push:
  pull_request:

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org

      - name: Install dependencies
        run: |
          echo "@fortawesome:registry=https://npm.fontawesome.com/" > .npmrc
          echo "//npm.fontawesome.com/:_authToken=${{ secrets.FONTAWESOME_NPM_AUTH_TOKEN }}" > .npmrc
          cat .npmrc
          yarn install

      - name: Run Prettier
        run: yarn prettier --check src

      - name: Run Lint
        run: yarn lint
